### ISSUE TITLE
Why stop updating

### ISSUE THREAD

**Issue by code871** [Akkariiin/ShadowsocksRR-android#2]
Why did you stop updating this project?It's a  regrettable news.

**Comment by Akkariiin** [comment]
not stop, it's only a delay, delaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaay .

**Comment by ZerOri** [comment]
确实非常简洁好用的ssr客户端，希望能继续维护下去！

**Comment by ZY714IU** [comment]
希望继续更新，感谢
